// src/gasp/utils/weekly-report.js

const PerformanceAnalyzer = require('./analysis');
const GAQL_QUERIES = require('./gaql-queries');

/**
 * Generate comprehensive weekly report
 */
async function generateWeeklyReport(googleAdsClient) {
  console.log('Generating weekly report...');

  const report = {
    week: new Date().toISOString().split('T')[0],
    gasp: {},
    performanceMax: {},
    comparison: {},
    insights: []
  };

  try {
    // Fetch campaign comparison data
    const comparisonData = await googleAdsClient.query(
      GAQL_QUERIES.CAMPAIGN_COMPARISON(7)
    );

    // Split by campaign type
    const gaspData = comparisonData.filter(row =>
      row.campaign.name.includes('GASP')
    );
    const pmaxData = comparisonData.filter(row =>
      row.campaign.name.includes('Performance Max') ||
      row.campaign.labels?.includes('PMAX-Control')
    );

    // Aggregate performance
    report.gasp = PerformanceAnalyzer.aggregateCampaignPerformance(gaspData);
    report.performanceMax = PerformanceAnalyzer.aggregateCampaignPerformance(pmaxData);

    // Calculate comparison
    report.comparison.cpaDifference = report.gasp.cpa && report.performanceMax.cpa
      ? ((report.gasp.cpa - report.performanceMax.cpa) / report.performanceMax.cpa) * 100
      : null;

    report.comparison.conversionsDifference =
      report.gasp.conversions - report.performanceMax.conversions;

    report.comparison.winner = report.gasp.cpa < report.performanceMax.cpa ? 'GASP' : 'Performance Max';

    // Add insights
    if (report.comparison.cpaDifference !== null) {
      if (report.comparison.cpaDifference < -20) {
        report.insights.push({
          type: 'SUCCESS',
          message: `GASP is winning with ${Math.abs(report.comparison.cpaDifference).toFixed(0)}% lower CPA`
        });
      } else if (report.comparison.cpaDifference > 20) {
        report.insights.push({
          type: 'WARNING',
          message: `GASP CPA is ${report.comparison.cpaDifference.toFixed(0)}% higher - investigate`
        });
      }
    }

    if (report.gasp.conversions === 0 && gaspData.length > 0) {
      report.insights.push({
        type: 'ALERT',
        message: 'GASP has zero conversions this week - check campaigns'
      });
    }

    console.log('✓ Weekly report generated');
    return report;

  } catch (error) {
    console.error('Failed to generate weekly report:', error);
    throw error;
  }
}

/**
 * Format report as Markdown for email
 */
function formatReportAsMarkdown(report) {
  return `# GASP Weekly Report
**Week of:** ${report.week}

## Performance Summary

### GASP Campaigns
- **Impressions:** ${report.gasp.impressions.toLocaleString()}
- **Clicks:** ${report.gasp.clicks}
- **Conversions:** ${report.gasp.conversions}
- **Cost:** $${report.gasp.cost.toFixed(2)}
- **CPA:** ${report.gasp.cpa ? '$' + report.gasp.cpa.toFixed(2) : 'N/A'}
- **CTR:** ${(report.gasp.ctr * 100).toFixed(2)}%
- **Conv Rate:** ${(report.gasp.conversionRate * 100).toFixed(2)}%

### Performance Max
- **Impressions:** ${report.performanceMax.impressions.toLocaleString()}
- **Clicks:** ${report.performanceMax.clicks}
- **Conversions:** ${report.performanceMax.conversions}
- **Cost:** $${report.performanceMax.cost.toFixed(2)}
- **CPA:** ${report.performanceMax.cpa ? '$' + report.performanceMax.cpa.toFixed(2) : 'N/A'}
- **CTR:** ${(report.performanceMax.ctr * 100).toFixed(2)}%
- **Conv Rate:** ${(report.performanceMax.conversionRate * 100).toFixed(2)}%

## Comparison

**Winner:** ${report.comparison.winner}

${report.comparison.cpaDifference !== null ?
  `**CPA Difference:** ${report.comparison.cpaDifference > 0 ? '+' : ''}${report.comparison.cpaDifference.toFixed(0)}%` :
  'Not enough data for CPA comparison'}

**Conversion Difference:** ${report.comparison.conversionsDifference > 0 ? '+' : ''}${report.comparison.conversionsDifference} bookings

## Insights

${report.insights.map(insight => `- **${insight.type}:** ${insight.message}`).join('\n')}

---

*Generated by GASP on ${new Date().toISOString()}*
`;
}

module.exports = { generateWeeklyReport, formatReportAsMarkdown };
